Repository khawajaazfar2000/Hacktoberfest2022-Repository-3, pull requests merged in 2022-10, with the labels that each got.

#1 first commit
  By function give Sum.cpp
  By function give Sum.exe
Labels: hacktoberfest

#2 done with it
  By function give Sum.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#4 READ & ARRAY FILE
  Arrays/.vscode/c_cpp_properties.json
  Arrays/.vscode/launch.json
  Arrays/.vscode/settings.json
  Arrays/2D_Array.cpp
  Arrays/Array_by_value.cpp
  Arrays/Array_reference.cpp
  Arrays/Random acess array.cpp
  Arrays/deletion_at_end.cpp
  Arrays/increasing_size_of_array_in_heap.cpp
  Arrays/largest_sum.cpp
  Arrays/random_number.cpp
  Arrays/tempCodeRunnerFile.cpp
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#5 Python code ADDED
  Pyhton/forloop.py
Labels: hacktoberfest, hacktoberfest-accepted

#6 Added quicksort in C++
  C++/quicksort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#7 Created bubblesort.py
  Pyhton/bubblesort.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#8 Code ADDED
  Javascript/program3.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#10 Dijsktra's Algorithm in C++
  C++/dijsktraalgo.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#11 Selection Sort in C++
  C++/Arrays/selectionsort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#12 Searching elements in array.cpp
  C++/Arrays/Searching_element_inarray.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#13 Insertion_Sort.cpp
  C++/Arrays/insertion_sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#14 Added a program to print Fibonacci series using iteration
  C++/cpp/Fibonacci_series.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#15 Added BFS
  C++/BFS.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#16 Create LeetCode-289. Game of Life.cpp
  C++/Arrays/LeetCode-289. Game of Life.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22
